### ISSUE TITLE
Broken NIFTI links

### ISSUE THREAD

**Issue by dgault** [ome/bio-formats-documentation#336]
The NIFTI links have been broken in the linkcheck tests for a while now: https://nifti.nimh.nih.gov/nifti-1/ 

So far I haven't been able to find a suitable alternative. @melissalinkert do you have any suggestions for alternative links?

**Comment by melissalinkert** [comment]
https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h is the closest to an official link that seems to still work. Maybe https://www.nitrc.org/docman/view.php/26/204/TheNIfTI too?
