### ISSUE TITLE
Option to disable bioformats importer

### ISSUE THREAD

**Issue by reiropke** [ome/bio-formats-documentation#389]
Is it possible for the developers to implement a way to prevent Bio-Formats from being forcefully used when not requested?

I just want to go to File > Open (Ctrl+O) and select images normally without being prompted by this intrusive plugin.

If this feature is already implemented, how can I do it with a single button, without needing to click on every single image format available on my computer?

**Comment by dgault** [comment]
Hi @reiropke, I am assuming this is for use in the FIJI environment? Are there particular formats you are looking to disable? What method are you hoping to use for opening these files?

For many formats the Bio-Formats Importer is largely integrated with the `File › Open` command of Fiji. However by default Fiji uses some built-in logic to open TIFF files, but this logic may fail with certain TIFFs. You can disable Bio-Formats for individual formats by going to `Plugins > Bio-Formats > Bio-Formats Plugins Configuration > Formats` and deselecting the `Enabled` option for each format.

**Comment by reiropke** [comment]
Hello @dgault, thank you for responding.

Currently, I am using the FIJI environment. My lab colleagues and I usually work with .jpeg and .TIFF formats, but there is a possibility of using other formats as well. I need to use the Bio-Formats Importer, but my colleagues do not. They would prefer not to see the Bio-Formats pop-up when opening images on the computer we share.

You mentioned that I can disable Bio-Formats for individual formats by going to Plugins > Bio-Formats > Bio-Formats Plugins Configuration > Formats and deselecting the Enabled option for each format. However, is there a way to deselect all formats at once?

I would like to use the Bio-Formats Importer only when specifically selecting it through Plugins > Bio-Formats > Bio-Formats Importer, regardless of the format. This would prevent any inconvenience to my colleagues who needs to open images individually.

Thank you!

**Comment by reiropke** [comment]
Okay, thx a lot for the help!!
sorry for any inconvenience :)
