### ISSUE TITLE
Getting error 'Unsupported major.minor version 52.0' using bioformats command line tools

### ISSUE THREAD

**Issue by cudmore** [ome/bio-formats-documentation#94]
I am trying to use bio-formats in general and right now bio-formats command line tools. Whenever I run a tool (bfconvert for example), I am getting the error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: loci/formats/tools/ImageConverter : Unsupported major.minor version 52.0

I am on macOS Mojave (10.14.3).

The tutorial on using command line tools looks deceptively simple and mentions how java is now bundled in the downloaded zip? Ok, great. HOw do I get it to work?

I tried to download/install the recent Java from Oracle but that did not solve the issue?

**Comment by dgault** [comment]
As of Bio-Formats 6.0.0 the minimum Java version is Java 8, this exception suggest it is trying to run with an older version. If you run `java -version` from the command line what result do you get?

**Comment by cudmore** [comment]
Thanks for the tip and it is now working. I already had Java 8 installed but needed to get the Java command line working by also installing the Java SDK. After installing 'Java SE Development Kit 12', the bftools commands are working. Thanks...
